### ISSUE TITLE
第三关捡完第一个道具后，出现卡顿，画面停滞

### ISSUE THREAD

**Issue by asja-aaa** [NeilKleistGao/Zelda-External-Assassin-Plan#2]
![微信截图_20190707160107](https://user-images.githubusercontent.com/52391237/60765670-92520000-a0d0-11e9-9f93-2420a2269129.png)

**Comment by NeilKleistGao** [comment]
你确定这是第三关……

**Comment by NeilKleistGao** [comment]
卡顿前进行了什么操作？

**Comment by asja-aaa** [comment]
我玩了俩次都卡了，第一次是捡了羽毛，然后以为可以过河，发现不能然后死了，等复活就卡住了
第二次是直接捡道具就卡






------------------ 原始邮件 ------------------
发件人: "NeilKleistGao"<notifications@github.com>;
发送时间: 2019年7月7日(星期天) 下午4:12
收件人: "NeilKleistGao/Zelda-External-Assassin-Plan"<Zelda-External-Assassin-Plan@noreply.github.com>;
抄送: "一班  马帅   二班 王晓克"<1980490930@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [NeilKleistGao/Zelda-External-Assassin-Plan] 第三关捡完第一个道具后，出现卡顿，画面停滞 (#2)




卡顿前进行了什么操作？

**Comment by asja-aaa** [comment]
是第四关




------------------ 原始邮件 ------------------
发件人: "NeilKleistGao"<notifications@github.com>;
发送时间: 2019年7月7日(星期天) 下午4:12
收件人: "NeilKleistGao/Zelda-External-Assassin-Plan"<Zelda-External-Assassin-Plan@noreply.github.com>;
抄送: "一班  马帅   二班 王晓克"<1980490930@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [NeilKleistGao/Zelda-External-Assassin-Plan] 第三关捡完第一个道具后，出现卡顿，画面停滞 (#2)




卡顿前进行了什么操作？

**Comment by NeilKleistGao** [comment]
把捡道具卡的界面发上来

**Comment by asja-aaa** [comment]
又捡了一遍，突然好了






------------------ 原始邮件 ------------------
发件人: "NeilKleistGao"<notifications@github.com>;
发送时间: 2019年7月7日(星期天) 下午4:25
收件人: "NeilKleistGao/Zelda-External-Assassin-Plan"<Zelda-External-Assassin-Plan@noreply.github.com>;
抄送: "马帅"<1980490930@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [NeilKleistGao/Zelda-External-Assassin-Plan] 第三关捡完第一个道具后，出现卡顿，画面停滞 (#2)




把捡道具卡的界面发上来

**Comment by NeilKleistGao** [comment]
如果再有截图下来，河道的问题我一会修复

**Comment by asja-aaa** [comment]
这次又坏了，原因是淹死之后，不能继续操作






------------------ 原始邮件 ------------------
发件人: "NeilKleistGao"<notifications@github.com>;
发送时间: 2019年7月7日(星期天) 下午4:25
收件人: "NeilKleistGao/Zelda-External-Assassin-Plan"<Zelda-External-Assassin-Plan@noreply.github.com>;
抄送: "马帅"<1980490930@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [NeilKleistGao/Zelda-External-Assassin-Plan] 第三关捡完第一个道具后，出现卡顿，画面停滞 (#2)




把捡道具卡的界面发上来

**Comment by asja-aaa** [comment]
ok






------------------ 原始邮件 ------------------
发件人: "NeilKleistGao"<notifications@github.com>;
发送时间: 2019年7月7日(星期天) 下午4:35
收件人: "NeilKleistGao/Zelda-External-Assassin-Plan"<Zelda-External-Assassin-Plan@noreply.github.com>;
抄送: "马帅"<1980490930@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [NeilKleistGao/Zelda-External-Assassin-Plan] 第三关捡完第一个道具后，出现卡顿，画面停滞 (#2)




如果再有截图下来，河道的问题我一会修复

**Comment by NeilKleistGao** [comment]
已修复

**Comment by NeilKleistGao** [comment]
已修复

**Comment by asja-aaa** [comment]
牛逼






------------------ 原始邮件 ------------------
发件人: "NeilKleistGao"<notifications@github.com>;
发送时间: 2019年7月7日(星期天) 下午4:50
收件人: "NeilKleistGao/Zelda-External-Assassin-Plan"<Zelda-External-Assassin-Plan@noreply.github.com>;
抄送: "马帅"<1980490930@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [NeilKleistGao/Zelda-External-Assassin-Plan] 第三关捡完第一个道具后，出现卡顿，画面停滞 (#2)




已修复
